"""initial migrations

Revision ID: a1aa1f172988
Revises: 
Create Date: 2023-07-02 10:16:30.617954

"""
import importlib

import sqlalchemy as sa
from alembic import op

module_name = "BOM-backend.app"
module = importlib.import_module(module_name)
extract_initial_data = module.extract_initial_data


# revision identifiers, used by Alembic.
revision = 'a1aa1f172988'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('sub_section', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('TCode', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('Parent', sa.String(length=50), nullable=True),
    sa.Column('module', sa.Boolean(), nullable=False),
    sa.Column('repeated', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('fig', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.Column('part', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('standard', sa.String(length=50), nullable=True),
    sa.Column('national_stock_number', sa.String(length=100), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('ATA_number', sa.String(length=100), nullable=True),
    sa.Column('weight_on_pcs', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('sap_code', sa.String(length=100), nullable=True),
    sa.Column('head_of_CVE', sa.String(length=100), nullable=True),
    sa.Column('CP', sa.Boolean(), nullable=False),
    sa.Column('CCL', sa.Boolean(), nullable=False),
    sa.Column('drawing_lvl_2', sa.Boolean(), nullable=False),
    sa.Column('ITP_and_SPc_of_material', sa.Boolean(), nullable=False),
    sa.Column('ITP_and_SPC_of_production_technology', sa.Boolean(), nullable=False),
    sa.Column('type_of_analysis', sa.Boolean(), nullable=False),
    sa.Column('prototype_part', sa.Boolean(), nullable=False),
    sa.Column('test', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    extract_initial_data()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state')
    op.drop_table('component_user')
    op.drop_table('component_log')
    op.drop_table('component')
    # ### end Alembic commands ###
